imports:
 - { resource: controllers.yml }
 - { resource: views.yml }
 - { resource: repositories.yml }
 - { resource: providers.yml }

services:
#    upkeep_app.example:
#        class: Upkeep\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
